CREATE TABLE usuarioS (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	watsapp VARCHAR(20) NOT NULL,
	email VARCHAR(100),
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

SELECT * FROM usuarios